"""change admin model

Revision ID: 024e81c1553e
Revises: af89feea9d7b
Create Date: 2025-10-26 22:59:16.097379

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "024e81c1553e"
down_revision: Union[str, Sequence[str], None] = "af89feea9d7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_admins_username"), table_name="admins")
    op.drop_column("admins", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admins",
        sa.Column(
            "username", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.create_index(op.f("ix_admins_username"), "admins", ["username"], unique=True)
    # ### end Alembic commands ###
